-- Game catalog writes (global `games` / `game_items` rows) are **not** exposed to arbitrary
-- authenticated clients. Seeding is performed by server API routes using the Supabase
-- service role (`/api/games/ensure`, `/api/game-items/ensure`).
--
-- RLS for these tables remains: SELECT for any authenticated user (see `030_games.sql`,
-- `032_game_items.sql`). Inserts/updates to the catalog bypass RLS via service role.
--
-- Historical note: this file used to define temporary
-- `games_insert_authed` / `game_items_insert_authed` policies. Those are removed; if your
-- database still has them, apply `supabase/migrations/20260125120000_game_hardening_rls.sql`.

-- Intentionally empty (policy removal lives in migration for existing DBs).
