-- 0001_init.sql
-- Purpose: initialize original core tables that are still retained in-repo.
--
-- Note: Supabase SQL editor does not support includes; this file is a
-- convenience for ordering. Apply the files in this order:
--
-- Historical note:
-- `supabase/tables/cards.sql` and `supabase/tables/practice_events.sql`
-- were removed after the game-based migration completed.
--
-- Apply the remaining files in this order:
-- 1) supabase/tables/010_user_settings.sql

-- Intentionally empty (ordering-only). See files above.
