-- 0004_roles.sql
-- Profiles (Superadmin), tutor/student links with status, studio join requests,
-- RLS for tutors reading linked students + supplemental tutor_student_links policies.
--
-- Apply in order:
--   1) supabase/tables/040_profiles.sql
--   2) supabase/tables/041_tutor_student_links_status.sql
--   3) supabase/tables/042_studio_tutor_join_requests.sql
--   4) supabase/tables/043_rls_tutor_practice_profiles.sql
--   5) supabase/tables/044_studio_owner_bootstrap.sql
--   6) supabase/tables/045_studio_student_join_requests.sql
--   7) supabase/tables/046_profiles_studio_peers.sql
--   8) supabase/tables/047_profiles_join_request_visibility.sql
--   9) supabase/tables/048_profiles_select_split.sql
--  10) supabase/tables/049_studio_memberships_rls_no_recursion.sql (ordering: 0005_studio_memberships_rls.sql)
--
-- After deploy: grant first Superadmin (see docs/DUOLINGO_FOR_JAZZ_PLAN.md).
-- Future schema changes: add new numbered migrations, not new versions of this file.
--
-- Intentionally empty (ordering-only). See files above.
